import { createClient } from '@supabase/supabase-js';
import { readFileSync } from 'fs';
import { join } from 'path';

try {
  const buf = readFileSync(join(process.cwd(), '.env.local'));
  const raw = buf[0]===0xff&&buf[1]===0xfe ? buf.slice(2).toString('utf16le') : buf.toString('utf-8');
  for (const line of raw.split(/\r\n|\n/)) {
    const t = line.replace(/^﻿/,'').trim();
    if (!t || t.startsWith('#')) continue;
    const eq = t.indexOf('=');
    if (eq===-1) continue;
    const k = t.slice(0,eq).trim();
    const v = t.slice(eq+1).trim().replace(/^["']|["']$/g,'');
    if (!process.env[k]) process.env[k] = v;
  }
} catch {}

const sb = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!,
  { auth: { persistSession: false } }
);

const SOURCE_CONSENSUS = "Consensus of the four Sunni schools (Hanafi, Maliki, Shafi'i, Hanbali); cf. Wahbah al-Zuhayli, al-Fiqh al-Islami wa Adillatuhu, vol. 3 (Kitab al-Zakah); Yusuf al-Qaradawi, Fiqh al-Zakah.";
const SOURCE_LIVESTOCK = "Hadith of Abu Bakr al-Siddiq on zakat of livestock (Sahih al-Bukhari); consensus scale across the four schools; cf. al-Zuhayli, al-Fiqh al-Islami wa Adillatuhu, vol. 3.";
const SOURCE_AGRICULTURE = "Hadith: \"laysa fima duna khamsati awsuqin sadaqah\" (Sahih al-Bukhari & Muslim) for the majority nisab view; Hanafi position per al-Marghinani, al-Hidayah; cf. al-Zuhewli, al-Fiqh al-Islami wa Adillatuhu, vol. 3.";

const rows = [
  {
    category_key: 'general', subcategory_key: 'eligibility_conditions',
    category_name_ar: 'الشروط العامة لوجوب الزكاة', category_name_en: 'General Conditions for Zakat Obligation',
    nisab_value: null, nisab_unit: null,
    nisab_description_ar: 'تشترك جميع أبواب الزكاة في شروط عامة: (1) الإسلام، (2) الحرية، (3) الملك التام للمال، (4) بلوغ النصاب، (5) أن يكون المال ناميًا/قابلاً للنماء (كالنقود والتجارة والمواشي والزروع)، (6) الفضل عن الحاجات الأساسية والدَّين في أموال النقد والتجارة.',
    nisab_description_en: 'All categories of zakat share common general conditions: (1) being Muslim, (2) being free, (3) full ownership of the wealth, (4) reaching the nisab, (5) the wealth being of a growing/productive nature (cash, trade goods, livestock, crops), and (6) surplus over basic needs and debts, for cash- and trade-based wealth.',
    zakat_rate: null,
    rate_description_ar: 'يختلف معدل الزكاة باختلاف نوع المال: 2.5% للنقود والذهب والفضة وعروض التجارة، نسب متدرجة للمواشي، 10% أو 5% للزروع والثمار بحسب كلفة السقي.',
    rate_description_en: 'The zakat rate differs by wealth type: 2.5% for cash, gold, silver, and trade goods; a graduated scale for livestock; and 10% or 5% for crops depending on irrigation cost.',
    hawl_required: null,
    hawl_notes_ar: 'يُشترط الحول القمري الكامل في النقود والذهب والفضة وعروض التجارة والمواشي، ولا يُشترط في زكاة الزروع والثمار (تجب عند الحصاد) ولا في الركاز والمعادن المستخرجة (تجب فورًا).',
    hawl_notes_en: 'A full lunar (Hijri) year is required for cash, gold, silver, trade goods, and livestock. It is not required for crops (due at harvest) nor for rikaz/extracted minerals (due immediately).',
    debt_deduction_applicable: null,
    debt_deduction_notes_ar: 'يُعتبر خصم الدَّين الحالّ في أموال النقد والذهب والفضة وعروض التجارة قبل حساب الزكاة عند جمهور الفقهاء، بخلاف زكاة الزروع والمواشي التي تُحسب على الناتج/الرؤوس مباشرة.',
    debt_deduction_notes_en: 'Deduction of currently-due debt applies to cash, gold, silver, and trade-good zakat per the majority of jurists, unlike crops and livestock, which are assessed directly on yield/head-count.',
    madhhab_scope: 'consensus',
    hanafi_difference_ar: 'يتوسّع الحنفية عمومًا في باب خصم الدَّين (حتى المؤجَّل منه) أكثر من غيرهم، ويخالفون الجمهور في عدم اشتراط نصاب للزروع.',
    hanafi_difference_en: 'The Hanafi school is generally more expansive on debt deduction (including deferred debt) than the other schools, and uniquely does not require a nisab minimum for agricultural produce.',
    source_reference: SOURCE_CONSENSUS,
    sort_order: 0,
  },
  {
    category_key: 'gold_silver', subcategory_key: 'gold',
    category_name_ar: 'الذهب', category_name_en: 'Gold',
    nisab_value: 85, nisab_unit: 'gram',
    nisab_description_ar: 'نصاب الذهب 85 جرامًا (يعادل 20 مثقالًا/دينارًا شرعيًا) من الذهب الخالص أو المصوغ. إذا بلغ الذهب المملوك هذا القدر أو زاد عليه وجبت فيه الزكاة.',
    nisab_description_en: "The nisab (minimum threshold) for gold is 85 grams (equivalent to 20 shar'i mithqals/dinars) of pure or fashioned gold. Zakat becomes obligatory once owned gold reaches or exceeds this amount.",
    zakat_rate: 0.025,
    rate_description_ar: 'يُزكّى الذهب بنسبة 2.5% (ربع العشر) من قيمته أو وزنه عند تمام الحول.',
    rate_description_en: "Gold is zakatable at 2.5% (one-fortieth) of its value or weight once the lunar year (hawl) is complete.",
    hawl_required: true,
    hawl_notes_ar: 'يُشترط مرور حول قمري كامل (سنة هجرية) على بلوغ النصاب، باتفاق المذاهب الأربعة.',
    hawl_notes_en: 'A complete lunar (Hijri) year of possession at or above the nisab is required — agreed upon by all four Sunni schools.',
    debt_deduction_applicable: true,
    debt_deduction_notes_ar: 'تُخصم الديون الحالّة المستحقة على المالك من قيمة الذهب قبل حساب الزكاة عند جمهور الفقهاء.',
    debt_deduction_notes_en: 'Debts currently due and owed by the owner are deducted from the value before calculating zakat, according to the majority of jurists.',
    madhhab_scope: 'consensus',
    hanafi_difference_ar: 'يرى الحنفية جواز خصم الديون المؤجَّلة أيضًا إلى جانب الديون الحالّة، وهم أوسع المذاهب في باب خصم الدَّين من الذمة قبل وجوب الزكاة.',
    hanafi_difference_en: 'The Hanafi school permits deducting deferred (not-yet-due) debts in addition to due debts, making it the most expansive school regarding debt deduction before zakat is assessed.',
    source_reference: SOURCE_CONSENSUS,
    sort_order: 1,
  },
  {
    category_key: 'gold_silver', subcategory_key: 'silver',
    category_name_ar: 'الفضة', category_name_en: 'Silver',
    nisab_value: 595, nisab_unit: 'gram',
    nisab_description_ar: 'نصاب الفضة 595 جرامًا (يعادل 200 درهم شرعي) من الفضة الخالصة أو المصوغة.',
    nisab_description_en: "The nisab for silver is 595 grams (equivalent to 200 shar'i dirhams) of pure or fashioned silver.",
    zakat_rate: 0.025,
    rate_description_ar: 'تُزكّى الفضة بنسبة 2.5% من قيمتها أو وزنها عند تمام الحول، كالذهب.',
    rate_description_en: 'Silver is zakatable at 2.5% of its value or weight once the lunar year is complete, the same rate as gold.',
    hawl_required: true,
    hawl_notes_ar: 'يُشترط مرور حول قمري كامل على بلوغ النصاب، باتفاق المذاهب الأربعة.',
    hawl_notes_en: 'A complete lunar year of possession at or above the nisab is required, agreed upon by all four schools.',
    debt_deduction_applicable: true,
    debt_deduction_notes_ar: 'تُخصم الديون الحالّة المستحقة على المالك من قيمة الفضة قبل حساب الزكاة عند جمهور الفقهاء.',
    debt_deduction_notes_en: 'Debts currently due and owed by the owner are deducted from the value before calculating zakat, according to the majority of jurists.',
    madhhab_scope: 'consensus',
    hanafi_difference_ar: 'يرى الحنفية جواز خصم الديون المؤجَّلة أيضًا إلى جانب الديون الحالّة، وهم أوسع المذاهب في باب خصم الدَّين من الذمة قبل وجوب الزكاة.',
    hanafi_difference_en: 'The Hanafi school permits deducting deferred debts in addition to due debts, making it the most expansive school regarding debt deduction before zakat is assessed.',
    source_reference: SOURCE_CONSENSUS,
    sort_order: 2,
  },
  {
    category_key: 'cash', subcategory_key: '',
    category_name_ar: 'النقود والمدخرات النقدية', category_name_en: 'Cash and Monetary Savings',
    nisab_value: 595, nisab_unit: 'gram_silver_equivalent',
    nisab_description_ar: 'يُقدَّر نصاب النقود (العملات والمدخرات المصرفية) بما يساوي قيمة نصاب الفضة (595 جرامًا)، وهو الأحوط والأكثر شيوعًا في الفتاوى المعاصرة لأنه أقل قيمة من نصاب الذهب فيشمل عددًا أكبر من المستحقين بالزكاة. وذهب بعض العلماء إلى تقدير نصاب النقود بقيمة نصاب الذهب (85 جرامًا) قياسًا على كونها أثمانًا كالدنانير الذهبية.',
    nisab_description_en: 'The nisab for cash (currency and bank savings) is conventionally valued against the silver nisab (595g), as this is the lower threshold and is considered more precautionary/inclusive in contemporary fatwas. Some scholars instead value cash against the gold nisab (85g), by analogy to cash functioning as currency akin to gold dinars.',
    zakat_rate: 0.025,
    rate_description_ar: 'تُزكّى النقود بنسبة 2.5% من إجمالي المبلغ الذي بلغ النصاب وحال عليه الحول.',
    rate_description_en: 'Cash is zakatable at 2.5% of the total amount that has reached the nisab and been held for a full lunar year.',
    hawl_required: true,
    hawl_notes_ar: 'يُشترط مرور حول قمري كامل على بلوغ النصاب، باتفاق المذاهب الأربعة.',
    hawl_notes_en: 'A complete lunar year of possession at or above the nisab is required, agreed upon by all four schools.',
    debt_deduction_applicable: true,
    debt_deduction_notes_ar: 'تُخصم الديون الحالّة المستحقة على الشخص من إجمالي النقود قبل حساب الزكاة؛ فإن بقي بعد الخصم ما يبلغ النصاب وجبت فيه الزكاة وإلا فلا.',
    debt_deduction_notes_en: 'Debts currently due are deducted from total cash before calculating zakat; zakat is owed only if the remainder still meets the nisab.',
    madhhab_scope: 'consensus',
    hanafi_difference_ar: 'يوسّع الحنفية في خصم الديون فيشمل الديون المؤجَّلة لا الحالّة فقط، بخلاف عامة المذاهب التي تقصر الخصم على الديون الحالّة المُطالَب بها.',
    hanafi_difference_en: 'The Hanafi school broadens debt deduction to include deferred debts, not only those currently due — unlike the other schools, which generally restrict deduction to debts presently demanded.',
    source_reference: "Majority/contemporary fiqh practice; cf. al-Qaradawi, Fiqh al-Zakah, ch. 3 (zakat on money); Permanent Committee for Islamic Research and Fatwa (Saudi Arabia), rulings on zakat al-nuqud.",
    sort_order: 3,
  },
  {
    category_key: 'business_assets', subcategory_key: '',
    category_name_ar: "عروض التجارة (الأصول التجارية)", category_name_en: "Business / Trade Assets ('Urud al-Tijarah)",
    nisab_value: 595, nisab_unit: 'gram_silver_equivalent',
    nisab_description_ar: 'يُقوَّم ما عند التاجر من بضائع وعروض معدة للبيع بسعر السوق وقت وجوب الزكاة، ويُعتبر نصابها كنصاب النقود (ما يعادل 595 جرامًا من الفضة)، باتفاق المذاهب الأربعة على أصل وجوب الزكاة في عروض التجارة.',
    nisab_description_en: 'Goods and assets held for trade are valued at current market price when zakat is assessed; their nisab is treated the same as cash (the silver-equivalent threshold). All four schools agree on the basic obligation of zakat on trade goods.',
    zakat_rate: 0.025,
    rate_description_ar: 'تُزكّى عروض التجارة بنسبة 2.5% من القيمة السوقية الصافية للبضاعة عند تمام الحول.',
    rate_description_en: 'Trade assets are zakatable at 2.5% of the net market value of the goods once the lunar year is complete.',
    hawl_required: true,
    hawl_notes_ar: 'يُشترط مرور حول قمري كامل على بلوغ النصاب، باتفاق المذاهب الأربعة.',
    hawl_notes_en: 'A complete lunar year of possession at or above the nisab is required, agreed upon by all four schools.',
    debt_deduction_applicable: true,
    debt_deduction_notes_ar: 'تُخصم ديون التاجر وخصومه التجارية المستحقة (كالمستحق للموردين) من قيمة البضاعة والنقد المتاح قبل حساب الزكاة عند جمهور الفقهاء.',
    debt_deduction_notes_en: 'Business liabilities currently due (e.g., amounts owed to suppliers) are deducted from inventory and available cash before assessing zakat, per the majority of jurists.',
    madhhab_scope: 'consensus',
    hanafi_difference_ar: 'يتوسّع الحنفية في اعتبار الديون المؤجَّلة المتعلقة بالتجارة ضمن ما يُخصم، بخلاف ضيق بعض المذاهب الأخرى في حصر الخصم بالديون الحالّة فقط.',
    hanafi_difference_en: 'The Hanafi school more broadly includes deferred trade-related debts among deductible liabilities, whereas some other schools restrict deduction to currently due debts only.',
    source_reference: "Consensus of the four schools on the obligation; cf. Ibn Rushd, Bidayat al-Mujtahid (comparative fiqh on zakat); al-Zuhayli, al-Fiqh al-Islami wa Adillatuhu, vol. 3.",
    sort_order: 4,
  },
  {
    category_key: 'livestock', subcategory_key: 'camels',
    category_name_ar: 'الإبل', category_name_en: 'Camels',
    nisab_value: 5, nisab_unit: 'head',
    nisab_description_ar: 'يبدأ نصاب الإبل من 5 رؤوس؛ فما دون ذلك لا زكاة فيه.',
    nisab_description_en: 'The nisab for camels begins at 5 head; fewer than this is not zakatable.',
    zakat_rate: null,
    rate_description_ar: 'تُزكّى الإبل وفق جدول متدرج: 5–9 رؤوس: شاة واحدة، 10–14: شاتان، 15–19: ثلاث شياه، 20–24: أربع شياه، 25–35: بنت مخاض (ابنة سنة)، 36–45: بنت لبون (ابنة سنتين)، 46–60: حِقّة (ابنة ثلاث سنين)، 61–75: جذعة (ابنة أربع سنين)، 76–90: بنتا لبون، 91–120: حِقّتان، وفيما زاد على ذلك: في كل 40 بنت لبون وفي كل 50 حِقّة.',
    rate_description_en: "Camels are zakatable on a graduated scale: 5–9 head: 1 sheep/goat; 10–14: 2 sheep; 15–19: 3 sheep; 20–24: 4 sheep; 25–35: 1 bint makhad (1-year-old she-camel); 36–45: 1 bint labun (2-year-old); 46–60: 1 hiqqah (3-year-old); 61–75: 1 jaza'ah (4-year-old); 76–90: 2 bint labun; 91–120: 2 hiqqah; beyond 120: 1 bint labun per additional 40, or 1 hiqqah per additional 50.",
    hawl_required: true,
    hawl_notes_ar: 'يُشترط الحول، وأن تكون الإبل "سائمة" (ترعى في الكلأ المباح أغلب السنة ولا تُعلَف غالبًا)، باتفاق المذاهب على اشتراط السوم وإن اختلفوا في تفاصيل ضابطه.',
    hawl_notes_en: 'A full lunar year is required, and the camels must be "sa\'imah" (grazing on natural pasture for most of the year rather than stall-fed); all schools require grazing-status, though they differ slightly on its precise definition.',
    debt_deduction_applicable: false,
    debt_deduction_notes_ar: 'لا تُحسب زكاة الإبل بالقيمة النقدية بل بعدد الرؤوس مباشرة، فلا يُجرى عليها خصم الدَّين كما يُجرى في النقود وعروض التجارة عند جمهور الفقهاء.',
    debt_deduction_notes_en: 'Zakat on camels is assessed by head count rather than monetary value, so debt deduction is not applied the way it is for cash or trade goods, according to the majority.',
    madhhab_scope: 'consensus',
    hanafi_difference_ar: 'لا يوجد خلاف جوهري بين المذاهب في جدول زكاة الإبل، وإنما خلافات دقيقة في بعض تفاصيل صفة السوم وسن الإبل المأخوذة.',
    hanafi_difference_en: 'There is no major disagreement among the schools on the camel zakat scale itself; differences are minor, relating to fine details of the grazing condition and exact age-classification of animals taken.',
    source_reference: SOURCE_LIVESTOCK,
    sort_order: 5,
  },
  {
    category_key: 'livestock', subcategory_key: 'cattle',
    category_name_ar: 'البقر', category_name_en: 'Cattle',
    nisab_value: 30, nisab_unit: 'head',
    nisab_description_ar: 'يبدأ نصاب البقر من 30 رأسًا.',
    nisab_description_en: 'The nisab for cattle begins at 30 head.',
    zakat_rate: null,
    rate_description_ar: '30–39 رأسًا: تبيع أو تبيعة (عجل/عجلة دخل في سنته الثانية)، 40–59: مُسِنّة (دخلت في سنتها الثالثة)، وما زاد: في كل 30 تبيع وفي كل 40 مُسِنّة.',
    rate_description_en: "30–39 head: 1 tabi'/tabi'ah (a calf entering its second year); 40–59: 1 musinnah (entering its third year); beyond that: 1 tabi' for every additional 30, and 1 musinnah for every additional 40.",
    hawl_required: true,
    hawl_notes_ar: 'يُشترط الحول، وأن تكون "سائمة" ترعى الكلأ المباح أغلب السنة.',
    hawl_notes_en: 'A full lunar year is required, and the cattle must be "sa\'imah" (grazing on natural pasture for most of the year).',
    debt_deduction_applicable: false,
    debt_deduction_notes_ar: 'لا تُحسب زكاة البقر بالقيمة النقدية بل بعدد الرؤوس مباشرة، فلا يُجرى عليها خصم الدَّين عند جمهور الفقهاء.',
    debt_deduction_notes_en: 'Zakat on cattle is assessed by head count rather than monetary value, so debt deduction is not applied, according to the majority.',
    madhhab_scope: 'consensus',
    hanafi_difference_ar: 'لا خلاف جوهري في جدول زكاة البقر بين المذاهب الأربعة.',
    hanafi_difference_en: 'No substantial disagreement exists among the four schools regarding the cattle zakat scale.',
    source_reference: SOURCE_LIVESTOCK,
    sort_order: 6,
  },
  {
    category_key: 'livestock', subcategory_key: 'sheep_goats',
    category_name_ar: 'الغنم والماعز', category_name_en: 'Sheep and Goats',
    nisab_value: 40, nisab_unit: 'head',
    nisab_description_ar: 'يبدأ نصاب الغنم والماعز من 40 رأسًا.',
    nisab_description_en: 'The nisab for sheep and goats begins at 40 head.',
    zakat_rate: null,
    rate_description_ar: '40–120 رأسًا: شاة واحدة، 121–200: شاتان، 201–300: ثلاث شياه، وما زاد على 300: شاة واحدة في كل مئة.',
    rate_description_en: '40–120 head: 1 sheep/goat; 121–200: 2; 201–300: 3; beyond 300: 1 additional sheep/goat for every additional 100.',
    hawl_required: true,
    hawl_notes_ar: 'يُشترط الحول، وأن تكون "سائمة" ترعى الكلأ المباح أغلب السنة.',
    hawl_notes_en: 'A full lunar year is required, and the flock must be "sa\'imah" (grazing on natural pasture for most of the year).',
    debt_deduction_applicable: false,
    debt_deduction_notes_ar: 'لا تُحسب زكاة الغنم بالقيمة النقدية بل بعدد الرؤوس مباشرة، فلا يُجرى عليها خصم الدَّين عند جمهور الفقهاء.',
    debt_deduction_notes_en: 'Zakat on sheep/goats is assessed by head count rather than monetary value, so debt deduction is not applied, according to the majority.',
    madhhab_scope: 'consensus',
    hanafi_difference_ar: 'لا خلاف جوهري بين المذاهب في جدول زكاة الغنم.',
    hanafi_difference_en: 'No substantial disagreement exists among the schools on the sheep/goat zakat scale.',
    source_reference: SOURCE_LIVESTOCK,
    sort_order: 7,
  },
  {
    category_key: 'agriculture', subcategory_key: 'rainfed',
    category_name_ar: 'الزروع والثمار المسقية بلا تكلفة (بماء المطر والأنهار)', category_name_en: 'Crops Irrigated Without Cost (rain, rivers, natural sources)',
    nisab_value: 5, nisab_unit: 'wasq',
    nisab_description_ar: "نصاب الزروع والثمار 5 أوسق (الوسق = 60 صاعًا)، وهو ما يُقدَّر تقريبًا بنحو 612–653 كجم من الحبوب أو التمر حسب اختلاف تقدير الصاع. وذهب الحنفية إلى عدم اشتراط نصاب أصلاً، فالعشر واجب في القليل والكثير من الخارج من الأرض.",
    nisab_description_en: "The nisab for crops and produce is 5 wasq (1 wasq = 60 sa'), approximately 612–653 kg of grain or dates depending on how the sa' is measured. The Hanafi school holds that no minimum nisab applies at all — the tithe (ushr) is due on whatever quantity the land produces, large or small.",
    zakat_rate: 0.10,
    rate_description_ar: "العشر (10%) فيما سُقي بلا تكلفة، كماء المطر والأنهار والعيون.",
    rate_description_en: "A tithe of 10% (al-'ushr) is due on produce irrigated without cost, such as by rainfall, rivers, or natural springs.",
    hawl_required: false,
    hawl_notes_ar: 'لا يُشترط الحول في زكاة الزروع والثمار؛ بل تجب الزكاة عند الحصاد/الجَذاذ كل مرة يُحصد فيها المحصول، باتفاق المذاهب الأربعة.',
    hawl_notes_en: 'No hawl (lunar year) is required for zakat on crops; it becomes due at the time of harvest each time the crop is reaped — agreed upon by all four schools.',
    debt_deduction_applicable: false,
    debt_deduction_notes_ar: 'لا تُخصم الديون من زكاة الزروع عند جمهور الفقهاء؛ لأنها تُحسب على الناتج الفعلي عند الحصاد لا على صافي الذمة المالية.',
    debt_deduction_notes_en: 'Debts are not deducted in calculating zakat on crops according to the majority, since it is assessed on the actual yield at harvest rather than net financial worth.',
    madhhab_scope: 'consensus_except_hanafi_on_nisab',
    hanafi_difference_ar: 'يخالف الحنفية الجمهور في شرط النصاب، فيوجبون العشر في كل ما تخرجه الأرض من قليل أو كثير دون تقدير 5 أوسق.',
    hanafi_difference_en: 'The Hanafi school differs from the majority specifically regarding the nisab requirement: it obligates the tithe on any amount the land produces, without requiring the 5-wasq threshold.',
    source_reference: SOURCE_AGRICULTURE,
    sort_order: 8,
  },
  {
    category_key: 'agriculture', subcategory_key: 'irrigated',
    category_name_ar: 'الزروع والثمار المسقية بتكلفة (الآلات والنواعير والشراء)', category_name_en: 'Crops Irrigated With Cost (machinery, waterwheels, purchased water)',
    nisab_value: 5, nisab_unit: 'wasq',
    nisab_description_ar: "نصاب الزروع والثمار 5 أوسق (الوسق = 60 صاعًا)، وهو ما يُقدَّر تقريبًا بنحو 612–653 كجم من الحبوب أو التمر حسب اختلاف تقدير الصاع. وذهب الحنفية إلى عدم اشتراط نصاب أصلاً، فالعشر واجب في القليل والكثير من الخارج من الأرض.",
    nisab_description_en: "The nisab for crops and produce is 5 wasq (1 wasq = 60 sa'), approximately 612–653 kg of grain or dates depending on how the sa' is measured. The Hanafi school holds that no minimum nisab applies at all — the tithe is due on whatever quantity the land produces, large or small.",
    zakat_rate: 0.05,
    rate_description_ar: 'نصف العشر (5%) فيما سُقي بتكلفة ومؤونة، كالسواني والنواعير والمضخات وشراء الماء.',
    rate_description_en: 'Half the tithe, 5% (nisf al-\'ushr), is due on produce irrigated at cost or effort, such as via waterwheels, pumps, machinery, or purchased water.',
    hawl_required: false,
    hawl_notes_ar: 'لا يُشترط الحول في زكاة الزروع والثمار؛ بل تجب الزكاة عند الحصاد/الجَذاذ كل مرة يُحصد فيها المحصول، باتفاق المذاهب الأربعة.',
    hawl_notes_en: 'No hawl is required for zakat on crops; it becomes due at the time of harvest each time the crop is reaped — agreed upon by all four schools.',
    debt_deduction_applicable: false,
    debt_deduction_notes_ar: 'لا تُخصم الديون من زكاة الزروع عند جمهور الفقهاء؛ لأنها تُحسب على الناتج الفعلي عند الحصاد لا على صافي الذمة المالية.',
    debt_deduction_notes_en: 'Debts are not deducted in calculating zakat on crops according to the majority, since it is assessed on the actual yield at harvest rather than net financial worth.',
    madhhab_scope: 'consensus_except_hanafi_on_nisab',
    hanafi_difference_ar: 'يخالف الحنفية الجمهور في شرط النصاب، فيوجبون العشر في كل ما تخرجه الأرض من قليل أو كثير دون تقدير 5 أوسق.',
    hanafi_difference_en: 'The Hanafi school differs from the majority on the nisab requirement: it obligates the tithe on any amount the land produces, without requiring the 5-wasq threshold.',
    source_reference: SOURCE_AGRICULTURE,
    sort_order: 9,
  },
];

async function main() {
  const { error, data } = await sb
    .from('library_zakat_rules')
    .upsert(rows, { onConflict: 'category_key,subcategory_key' })
    .select('id');
  if (error) { console.error('Insert error:', error.message); process.exit(1); }
  console.log(`Upserted ${data?.length ?? 0} rows.`);
}
main().catch(e => { console.error(e.message); process.exit(1); });
